# Generated by Django 3.2.2 on 2021-05-07 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comentarios', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comentario',
            old_name='nome_comentairio',
            new_name='nome_comentario',
        ),
    ]
