# Generated by Django 3.2.2 on 2021-05-07 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='nome_cat',
            field=models.CharField(max_length=70, verbose_name='Categoria'),
        ),
    ]
